# Generated by Django 2.0 on 2019-01-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/%Y/', verbose_name='Capa'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/%Y/', verbose_name='Foto'),
        ),
    ]
