# Generated by Django 2.0 on 2019-02-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_auto_20190209_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='default_foto.png', null=True, upload_to='imagens/%Y/', verbose_name='Foto'),
        ),
    ]
