# Generated by Django 2.0 on 2019-01-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_auto_20190104_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='usuario',
            new_name='autor',
        ),
    ]
