# Generated by Django 2.0 on 2019-02-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_colecao_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='capa',
            field=models.ImageField(blank=True, default='default_capa.jpg', null=True, upload_to='imagens/%Y/', verbose_name='Capa'),
        ),
    ]
