# Generated by Django 2.0 on 2019-01-04 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_auto_20190104_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='usuario',
        ),
    ]
