# Generated by Django 2.0 on 2019-01-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0004_auto_20190104_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='imagens/default/default_foto.png', null=True, upload_to='imagens/%Y/', verbose_name='Foto'),
        ),
    ]
