# Generated by Django 2.0 on 2019-01-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0005_auto_20190104_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='default_foto.png', null=True, upload_to='imagens/%Y/', verbose_name='Foto'),
        ),
    ]
