# Generated by Django 2.0 on 2019-01-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0006_auto_20190104_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='qtd_amigos',
            field=models.IntegerField(default=0, verbose_name='Quantidade Amigos'),
        ),
    ]
