# Generated by Django 2.0 on 2019-01-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0007_perfil_qtd_amigos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='capa',
            field=models.ImageField(blank=True, default='default/default_capa.jpg', null=True, upload_to='imagens/%Y/', verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='default/default_foto.png', null=True, upload_to='imagens/%Y/', verbose_name='Foto'),
        ),
    ]
