# Generated by Django 2.0 on 2019-01-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0008_auto_20190104_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='qtd_amigos',
        ),
    ]
