# Generated by Django 2.0 on 2019-01-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0015_post_nome_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nome_autor',
        ),
    ]
