# Generated by Django 2.0 on 2019-01-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0016_remove_post_nome_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='default/default_foto.png', null=True, upload_to='imagens/%Y/', verbose_name='Foto'),
        ),
    ]
