# Generated by Django 2.0 on 2019-01-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0018_auto_20190105_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='capa',
            field=models.ImageField(blank=True, default='default_capa.jpg', null=True, upload_to='imagens/%Y/', verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='default_foto.png', null=True, upload_to='imagens/%Y/', verbose_name='Foto'),
        ),
    ]
