# Generated by Django 2.0 on 2019-01-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0019_auto_20190105_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='anexo',
        ),
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='arquivos/%Y/posts/', verbose_name='Foto'),
        ),
    ]
