# Generated by Django 2.0 on 2019-01-09 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0022_auto_20190108_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
