# Generated by Django 2.0 on 2019-01-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0023_auto_20190108_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('criado_em',)},
        ),
    ]
